spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ET_DB  # MySQL 데이터베이스 URL
    username: root  # 데이터베이스 사용자
    password : 1234
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC 드라이버

  jpa:
    hibernate:
      ddl-auto: update  # 데이터베이스 테이블 업데이트 전략

  security:
    user:
      name: admin  # 기본 관리자 사용자
      password: adminpass  # 기본 관리자 비밀번호

  messages:
    basename: messages  # 국제화 파일의 기본 이름

  cache:
    type: simple  # 캐시 유형

server:
  port: 8080  # 애플리케이션 서버 포트 번호

logging:
  level:
    org.springframework: INFO  # Spring 프레임워크 로깅 수준
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"  # 콘솔 로그 형식
